name: Unit Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install -g pnpm && pnpm install 
    - name: Run tests
      id: run-tests 
      run: pnpm exec jest --json --outputFile=unit-tests.json || true
    - name: Generate HTML report
      if: steps.run-tests.outputs.tests_failed == 'true'
      run: npx jest-html-reporter --json unit-tests.json --output unit-tests-report.html
    - uses: actions/upload-artifact@v4
      if: steps.run-tests.outputs.tests_failed == 'true'
      with:
        name: unit-tests
        path: |
          unit-tests.json
          unit-tests-report.html
        retention-days: 30